# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_2025',
                'doc_host': 'https://joseeguizportillo.github.io',
                'git_url': 'https://github.com/joseeguizportillo/nbdev_2025',
                'lib_path': 'nbdev_2025'},
  'syms': {'nbdev_2025.core': {'nbdev_2025.core.foo': ('core.html#foo', 'nbdev_2025/core.py')}}}
